[
    {
      "id": "8f52dc5b-cc14-4584-90c8-4e78b070eb30",
      "type": "CUSTOM",
      "ver": "3.0",
      "name": "Тесты",
      "icon": "mt.png",
      "desc": "Тесты",
      "files": {
          "mid": "00000000-0000-0000-0000-000000000000",
          "sid": "00000000-0000-0000-0000-000000000000",
          "jrn": false,
          "osc": false
      },
      "reports": {
          "state": false,
          "maint": false
      },
      "altname": "",
      "states": [
          {
              "visible": false,
              "system": false,
              "id": "673827c4-832c-4c2d-9475-6ea6dc6fccf8",
              "name": "UNKNOWN",
              "desc": "Неопределенное",
              "link": "",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 0,
              "state": true,
              "$count": 0,
              "$parent": 1725374914030,
              "$level": 3
          },
          {
              "visible": false,
              "system": true,
              "id": "ff5da69a-70f5-4b78-b20e-fc9cd5f09ce2",
              "name": "$MAINT_WARN",
              "desc": "Необходимо обслуживание",
              "link": "ff5da69a-70f5-4b78-b20e-fc9cd5f09ce2",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 3,
              "state": true,
              "$count": 0,
              "$parent": 1725374914030,
              "$level": 3
          },
          {
              "visible": false,
              "system": true,
              "id": "67dcf875-09a4-4ce1-8066-dbcfb4f3e8db",
              "name": "$MAINT_ALARM",
              "desc": "Аварийное (необходимо обслуживание)",
              "link": "67dcf875-09a4-4ce1-8066-dbcfb4f3e8db",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 3,
              "state": true,
              "$count": 0,
              "$parent": 1725374914030,
              "$level": 3
          }
      ],
      "commands": [],
      "oper": [
          {
              "scale": "",
              "action": 1,
              "m": "",
              "id": "57510ccc-c2ea-44a8-a26c-cb799bba269f",
              "name": "1",
              "desc": "1",
              "link": "DatabaseTags.Group1.1",
              "db": true,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 9,
              "$count": 0,
              "$parent": 1725374914031,
              "$level": 3
          },
          {
              "scale": "",
              "action": 1,
              "m": "",
              "id": "9c406da5-825f-45ee-b901-49a38a265c35",
              "name": "2",
              "desc": "2",
              "link": "DatabaseTags.Group1.2",
              "db": true,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 14,
              "$count": 0,
              "$parent": 1725374914031,
              "$level": 3
          },
          {
              "scale": "",
              "action": 1,
              "m": "",
              "id": "7426a624-24bd-4a0b-8713-6b549da83b88",
              "name": "Текущее время",
              "desc": "Текущее время",
              "link": "HOST.CurrentTime",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 16,
              "$count": 0,
              "$parent": 1725374914031,
              "$level": 3
          },
          {
              "scale": "",
              "action": 1,
              "m": "",
              "id": "2c4516bc-a6d8-40a6-8466-fa1b50d708b6",
              "name": "Время работы",
              "desc": "Время работы",
              "link": "HOST.WorkTime",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 102,
              "$count": 0,
              "$parent": 1725374914031,
              "$level": 3
          },
          {
              "scale": "",
              "action": 1,
              "m": "%",
              "id": "529453db-4891-4458-a326-084a00d3d55d",
              "name": "Загрузка ЦП процессом",
              "desc": "Загрузка ЦП процессом",
              "link": "HOST.Resources.CPU.Process",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 14,
              "$count": 0,
              "$parent": 1725374914031,
              "$level": 3
          }
      ],
      "passport": {
          "staticData": [],
          "parameters": []
      },
      "maintenance": {
          "enabled": false,
          "isAcknowledged": false,
          "triggeredParameters": [],
          "source": 0,
          "warningDate": "2023-12-06T12:59:28.6160000Z",
          "alarmDate": "2023-12-06T12:59:28.6160000Z",
          "parameters": [],
          "isPending": false
      },
      "pages": [],
      "state": "UNKNOWN",
      "eq": true,
      "$count": 15,
      "$parent": 0,
      "$level": 1
  },
  {
      "id": "1f769cdc-8e28-4b5f-8b13-6f102cbe086c",
      "type": "CUSTOM",
      "ver": "3.0",
      "name": "Тест План",
      "icon": "mt.png",
      "desc": "Тест План",
      "files": {
          "mid": "00000000-0000-0000-0000-000000000000",
          "sid": "00000000-0000-0000-0000-000000000000",
          "jrn": false,
          "osc": false
      },
      "reports": {
          "state": false,
          "maint": false
      },
      "altname": "",
      "states": [
          {
              "visible": false,
              "system": false,
              "id": "5f5cf71d-a499-439e-b342-32b8bd4b23b3",
              "name": "UNKNOWN",
              "desc": "Неопределенное",
              "link": "",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 0,
              "state": true,
              "$count": 0,
              "$parent": 1725374914366,
              "$level": 3
          },
          {
              "visible": false,
              "system": true,
              "id": "f9cdb3b1-c15a-46ba-ab1b-a78cc9c69572",
              "name": "$MAINT_WARN",
              "desc": "Необходимо обслуживание",
              "link": "f9cdb3b1-c15a-46ba-ab1b-a78cc9c69572",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 3,
              "state": true,
              "$count": 0,
              "$parent": 1725374914366,
              "$level": 3
          },
          {
              "visible": false,
              "system": true,
              "id": "1fbadaff-3681-410f-bccf-26b82da4e441",
              "name": "$MAINT_ALARM",
              "desc": "Аварийное (необходимо обслуживание)",
              "link": "1fbadaff-3681-410f-bccf-26b82da4e441",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 3,
              "state": true,
              "$count": 0,
              "$parent": 1725374914366,
              "$level": 3
          }
      ],
      "commands": [
          {
              "icon": "cmd/default.png",
              "cnf": true,
              "id": "7d9040df-b199-4776-87d2-18b27ea7d7cc",
              "name": "МУ_вкл",
              "desc": "МУ_вкл",
              "link": "VirtualDevices.Group.Device2.Commands.МУ_вкл",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 3,
              "cmd": true,
              "$count": 0,
              "$parent": 1725374914367,
              "$level": 3
          },
          {
              "icon": "cmd/default.png",
              "cnf": true,
              "id": "8d085bee-e311-4c9f-a36f-f7b29f7dfb1a",
              "name": "МУ_откл",
              "desc": "МУ_откл",
              "link": "VirtualDevices.Group.Device2.Commands.МУ_откл",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 3,
              "cmd": true,
              "$count": 0,
              "$parent": 1725374914367,
              "$level": 3
          }
      ],
      "oper": [
          {
              "scale": "",
              "action": 1,
              "m": "",
              "id": "aff03344-bd47-4bf0-893c-462fd36c091d",
              "name": "t1",
              "desc": "t1",
              "link": "DatabaseTags.Group1.1",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 9,
              "$count": 0,
              "$parent": 1725374914368,
              "$level": 3
          },
          {
              "scale": "",
              "action": 1,
              "m": "",
              "id": "cf37e950-151d-4a7d-b3b0-081f6b4817ca",
              "name": "t2",
              "desc": "t2",
              "link": "DatabaseTags.Group1.2",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 14,
              "$count": 0,
              "$parent": 1725374914368,
              "$level": 3
          },
          {
              "scale": "",
              "action": 1,
              "m": "",
              "id": "23a65fa9-5d65-4072-99cd-8f3e7284fb2e",
              "name": "t3",
              "desc": "t3",
              "link": "DatabaseTags.Group1.3",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 18,
              "$count": 0,
              "$parent": 1725374914368,
              "$level": 3
          },
          {
              "scale": "",
              "action": 1,
              "m": "",
              "id": "b31cc16b-31dc-45ad-8011-6a903d2cc7c4",
              "name": "t4",
              "desc": "t4",
              "link": "DatabaseTags.Group1.4",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 16,
              "$count": 0,
              "$parent": 1725374914368,
              "$level": 3
          },
          {
              "scale": "",
              "action": 1,
              "m": "",
              "id": "dcc5e252-5fe2-473a-a8cf-aee37066a786",
              "name": "t5",
              "desc": "t5",
              "link": "DatabaseTags.Group1.5",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 3,
              "$count": 0,
              "$parent": 1725374914368,
              "$level": 3
          },
          {
              "scale": "",
              "action": 1,
              "m": "",
              "id": "02f50052-1269-4605-855e-47529eb61bb3",
              "name": "Текущее состояние",
              "desc": "Текущее состояние",
              "link": "DatabaseTags.Group1.State",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 110,
              "$count": 0,
              "$parent": 1725374914368,
              "$level": 3
          },
          {
              "scale": "",
              "action": 1,
              "m": "",
              "id": "60f24743-dfe6-4a88-97ce-b117df866c85",
              "name": "Бит состояния",
              "desc": "Бит состояния",
              "link": "DatabaseTags.Group1.StateBit",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 3,
              "$count": 0,
              "$parent": 1725374914368,
              "$level": 3
          },
          {
              "scale": "",
              "action": 1,
              "m": "",
              "id": "afc09901-9ca0-429b-9f80-144abc3d3cb1",
              "name": "tag_1",
              "desc": "tag_1",
              "link": "DatabaseTags.Group1.tag_1",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 14,
              "$count": 0,
              "$parent": 1725374914368,
              "$level": 3
          },
          {
              "scale": "",
              "action": 1,
              "m": "",
              "id": "e8d5df7c-65d1-4058-9e13-bdf3406f2f03",
              "name": "tag_In_Out",
              "desc": "tag_In_Out",
              "link": "DatabaseTags.Group1.tag_In_Out",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 14,
              "$count": 0,
              "$parent": 1725374914368,
              "$level": 3
          },
          {
              "scale": "",
              "action": 1,
              "m": "",
              "id": "a55e89ed-7984-4bed-8a25-8433001e6098",
              "name": "Текущее состояние",
              "desc": "Текущее состояние",
              "link": "DatabaseTags.State",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 110,
              "$count": 0,
              "$parent": 1725374914368,
              "$level": 3
          },
          {
              "scale": "",
              "action": 1,
              "m": "",
              "id": "5a7c8b2b-a5c9-4caf-85cb-880959df52bf",
              "name": "Бит состояния",
              "desc": "Бит состояния",
              "link": "DatabaseTags.StateBit",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 3,
              "$count": 0,
              "$parent": 1725374914368,
              "$level": 3
          },
          {
              "scale": "",
              "action": 1,
              "m": "",
              "id": "9e907786-8e1d-4510-91d5-4ae143a5a3af",
              "name": "1",
              "desc": "1",
              "link": "DatabaseTags.Group1.1",
              "db": true,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 9,
              "$count": 0,
              "$parent": 1725374914368,
              "$level": 3
          },
          {
              "scale": "",
              "action": 1,
              "m": "",
              "id": "2a28b65f-232a-464f-8c47-2bcd76cf4cb7",
              "name": "2",
              "desc": "2",
              "link": "DatabaseTags.Group1.2",
              "db": true,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 14,
              "$count": 0,
              "$parent": 1725374914368,
              "$level": 3
          }
      ],
      "passport": {
          "staticData": [],
          "parameters": []
      },
      "maintenance": {
          "enabled": false,
          "isAcknowledged": false,
          "triggeredParameters": [],
          "source": 0,
          "warningDate": "2023-10-11T09:31:34.5260000Z",
          "alarmDate": "2023-10-11T09:31:34.5260000Z",
          "parameters": [],
          "isPending": false
      },
      "pages": [],
      "state": "UNKNOWN",
      "eq": true,
      "$count": 11,
      "$parent": 0,
      "$level": 1
  },
  {
      "id": "ad8397d4-cd97-4bb2-b3d1-a2e238c32105",
      "type": "CUSTOM",
      "ver": "3.0",
      "name": "Тест скриптов",
      "icon": "mt.png",
      "desc": "Тест скриптов",
      "files": {
          "mid": "00000000-0000-0000-0000-000000000000",
          "sid": "00000000-0000-0000-0000-000000000000",
          "jrn": false,
          "osc": false
      },
      "reports": {
          "state": false,
          "maint": false
      },
      "altname": "",
      "states": [
          {
              "visible": false,
              "system": false,
              "id": "1b340de4-80ad-48ab-a551-6a201ea0dd96",
              "name": "UNKNOWN",
              "desc": "Неопределенное",
              "link": "",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 0,
              "state": true,
              "$count": 0,
              "$parent": 1725374914410,
              "$level": 3
          },
          {
              "visible": false,
              "system": true,
              "id": "de9ba4b2-ed13-46f8-b176-681b8435ae9e",
              "name": "$MAINT_WARN",
              "desc": "Необходимо обслуживание",
              "link": "de9ba4b2-ed13-46f8-b176-681b8435ae9e",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 3,
              "state": true,
              "$count": 0,
              "$parent": 1725374914410,
              "$level": 3
          },
          {
              "visible": false,
              "system": true,
              "id": "7810c830-1b12-477c-bfcd-dfa287e28e1c",
              "name": "$MAINT_ALARM",
              "desc": "Аварийное (необходимо обслуживание)",
              "link": "7810c830-1b12-477c-bfcd-dfa287e28e1c",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 3,
              "state": true,
              "$count": 0,
              "$parent": 1725374914410,
              "$level": 3
          }
      ],
      "commands": [],
      "oper": [
          {
              "scale": "",
              "action": 1,
              "m": "",
              "id": "c07c4801-7f27-48ba-b627-f225eeb6dc93",
              "name": "bool-eq-var",
              "desc": "bool-eq-var",
              "link": "DatabaseTags.qa-scripts.bool-db-tag",
              "db": true,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 3,
              "$count": 0,
              "$parent": 1725374914411,
              "$level": 3
          },
          {
              "scale": "",
              "action": 1,
              "m": "",
              "id": "b0fd7c5c-40ea-4363-8944-7a5e5cb3b9f9",
              "name": "dt-eq-tag",
              "desc": "dt-eq-tag",
              "link": "DatabaseTags.qa-scripts.dt-db-tag",
              "db": true,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 16,
              "$count": 0,
              "$parent": 1725374914411,
              "$level": 3
          },
          {
              "scale": "",
              "action": 1,
              "m": "",
              "id": "1bcd7a89-a4bf-4700-82a2-87a2c543f449",
              "name": "float-eq-tag",
              "desc": "float-eq-tag",
              "link": "DatabaseTags.qa-scripts.float-db-tag",
              "db": true,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 14,
              "$count": 0,
              "$parent": 1725374914411,
              "$level": 3
          },
          {
              "scale": "",
              "action": 1,
              "m": "",
              "id": "d00ad57a-b559-4d24-82c2-d287d78ee306",
              "name": "float-eq-tag2",
              "desc": "float-eq-tag2",
              "link": "DatabaseTags.qa-scripts.float-db-tag2",
              "db": true,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 14,
              "$count": 0,
              "$parent": 1725374914411,
              "$level": 3
          },
          {
              "scale": "",
              "action": 1,
              "m": "",
              "id": "ca57cd67-7c9f-4bc2-bc9c-e91f4298b1ca",
              "name": "int-eq-tag",
              "desc": "int-eq-tag",
              "link": "DatabaseTags.qa-scripts.int-db-tag",
              "db": true,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 9,
              "$count": 0,
              "$parent": 1725374914411,
              "$level": 3
          },
          {
              "scale": "",
              "action": 1,
              "m": "",
              "id": "b42c9260-cc2b-4feb-8cd2-e9a99537336b",
              "name": "str-eq-tag",
              "desc": "str-eq-tag",
              "link": "DatabaseTags.qa-scripts.str-db-tag",
              "db": true,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 18,
              "$count": 0,
              "$parent": 1725374914411,
              "$level": 3
          },
          {
              "scale": "",
              "action": 1,
              "m": "",
              "id": "f9017b2e-ac70-4816-89fa-295ff8940e95",
              "name": "SIN parameter",
              "desc": "SIN parameter",
              "link": "VirtualDevices.Group.Device1.Parameter.P_SIN",
              "db": true,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 14,
              "$count": 0,
              "$parent": 1725374914411,
              "$level": 3
          }
      ],
      "passport": {
          "staticData": [],
          "parameters": []
      },
      "maintenance": {
          "enabled": false,
          "isAcknowledged": false,
          "triggeredParameters": [],
          "source": 0,
          "warningDate": "2024-02-16T08:23:29.7770000Z",
          "alarmDate": "2024-02-16T08:23:29.7770000Z",
          "parameters": [],
          "isPending": false
      },
      "pages": [],
      "state": "UNKNOWN",
      "eq": true,
      "$count": 2,
      "$parent": 0,
      "$level": 1
  },
  {
      "id": "0c8f49b7-cda6-4362-8dec-6d22fce0a861",
      "type": "CUSTOM",
      "ver": "3.0",
      "name": "План-факт-прогноз",
      "icon": "mt.png",
      "desc": "План-факт-прогноз",
      "files": {
          "mid": "00000000-0000-0000-0000-000000000000",
          "sid": "00000000-0000-0000-0000-000000000000",
          "jrn": false,
          "osc": false
      },
      "reports": {
          "state": false,
          "maint": false
      },
      "altname": "",
      "states": [
          {
              "visible": false,
              "system": false,
              "id": "9ede2194-035b-42a8-969c-13a2b3c35a71",
              "name": "UNKNOWN",
              "desc": "Неопределенное",
              "link": "",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 0,
              "state": true,
              "$count": 0,
              "$parent": 1725374914412,
              "$level": 3
          },
          {
              "visible": false,
              "system": true,
              "id": "1f10c218-e992-4ba0-a8bc-4eb4a3f4fcb7",
              "name": "$MAINT_WARN",
              "desc": "Необходимо обслуживание",
              "link": "1f10c218-e992-4ba0-a8bc-4eb4a3f4fcb7",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 3,
              "state": true,
              "$count": 0,
              "$parent": 1725374914412,
              "$level": 3
          },
          {
              "visible": false,
              "system": true,
              "id": "bdb6f964-7343-4f24-8e79-e374cde49879",
              "name": "$MAINT_ALARM",
              "desc": "Аварийное (необходимо обслуживание)",
              "link": "bdb6f964-7343-4f24-8e79-e374cde49879",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 3,
              "state": true,
              "$count": 0,
              "$parent": 1725374914412,
              "$level": 3
          }
      ],
      "commands": [],
      "oper": [],
      "passport": {
          "staticData": [],
          "parameters": []
      },
      "maintenance": {
          "enabled": false,
          "isAcknowledged": false,
          "triggeredParameters": [],
          "source": 0,
          "warningDate": "2024-02-16T08:23:34.7180000Z",
          "alarmDate": "2024-02-16T08:23:34.7180000Z",
          "parameters": [],
          "isPending": false
      },
      "pages": [],
      "state": "UNKNOWN",
      "eq": true,
      "$count": 1,
      "$parent": 0,
      "$level": 1
  },
  {
      "id": "f100e65d-52a0-4f18-a8fa-f30fcbd8189f",
      "type": "CUSTOM",
      "ver": "3.0",
      "name": "ЭКОМ-3000",
      "icon": "mt.png",
      "desc": "ЭКОМ-3000",
      "files": {
          "mid": "00000000-0000-0000-0000-000000000000",
          "sid": "00000000-0000-0000-0000-000000000000",
          "jrn": false,
          "osc": false
      },
      "reports": {
          "state": false,
          "maint": false
      },
      "altname": "",
      "states": [
          {
              "visible": false,
              "system": false,
              "id": "b7410c2f-65a3-40a8-9a6c-b4f2667286f4",
              "name": "UNKNOWN",
              "desc": "Неопределенное",
              "link": "",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 0,
              "state": true,
              "$count": 0,
              "$parent": 1725374914413,
              "$level": 3
          },
          {
              "visible": false,
              "system": true,
              "id": "9b41ce8c-b402-42a6-85a9-be37f00ced5c",
              "name": "$MAINT_WARN",
              "desc": "Необходимо обслуживание",
              "link": "9b41ce8c-b402-42a6-85a9-be37f00ced5c",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 3,
              "state": true,
              "$count": 0,
              "$parent": 1725374914413,
              "$level": 3
          },
          {
              "visible": false,
              "system": true,
              "id": "6b5eda6c-9df4-47d8-8a49-6fd28cdceb93",
              "name": "$MAINT_ALARM",
              "desc": "Аварийное (необходимо обслуживание)",
              "link": "6b5eda6c-9df4-47d8-8a49-6fd28cdceb93",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 3,
              "state": true,
              "$count": 0,
              "$parent": 1725374914413,
              "$level": 3
          }
      ],
      "commands": [],
      "oper": [
          {
              "scale": "",
              "action": 1,
              "m": "",
              "id": "62a4a719-7db0-4f0c-b48a-452fa230e248",
              "name": "Количество попыток установления связи (полученных ошибок c кодом 404)",
              "desc": "Количество попыток установления связи (полученных ошибок c кодом 404)",
              "link": "ECOM3000.10_114_192_34_80.Diagnostics.Ans404Count",
              "db": true,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 0,
              "$count": 0,
              "$parent": 1725374914414,
              "$level": 3
          },
          {
              "scale": "",
              "action": 1,
              "m": "",
              "id": "0c07cb9e-8de1-4a49-8f82-335c8041f086",
              "name": "Счетчик количества полученных ответов с ошибками (в том числе и ответов с ошибками http)",
              "desc": "Счетчик количества полученных ответов с ошибками (в том числе и ответов с ошибками http)",
              "link": "ECOM3000.10_114_192_34_80.Diagnostics.AnswerErrorsCount",
              "db": true,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 0,
              "$count": 0,
              "$parent": 1725374914414,
              "$level": 3
          },
          {
              "scale": "",
              "action": 1,
              "m": "",
              "id": "2f707f24-6750-4384-8072-bd0483bc8b0d",
              "name": "Число тэгов выбранных для подписки",
              "desc": "Число тэгов выбранных для подписки",
              "link": "ECOM3000.10_114_192_34_80.Diagnostics.CheckedTagsCount",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 0,
              "$count": 0,
              "$parent": 1725374914414,
              "$level": 3
          },
          {
              "scale": "",
              "action": 1,
              "m": "",
              "id": "72bf3e1d-ce16-40cf-86a5-1aeff937d703",
              "name": "Количество принятых пакетов",
              "desc": "Количество принятых пакетов",
              "link": "ECOM3000.10_114_192_34_80.Diagnostics.ReceivedPackets",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 0,
              "$count": 0,
              "$parent": 1725374914414,
              "$level": 3
          },
          {
              "scale": "",
              "action": 1,
              "m": "",
              "id": "950bf8d9-50bb-4382-913e-691fb6595875",
              "name": "Количество переданных пакетов",
              "desc": "Количество переданных пакетов",
              "link": "ECOM3000.10_114_192_34_80.Diagnostics.SentPackets",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 0,
              "$count": 0,
              "$parent": 1725374914414,
              "$level": 3
          },
          {
              "scale": "",
              "action": 1,
              "m": "",
              "id": "2f17526a-5ac3-4929-97fc-f4f53a74edd4",
              "name": "Количество ошибок ожидания (превышение таймаута ожидания)",
              "desc": "Количество ошибок ожидания (превышение таймаута ожидания)",
              "link": "ECOM3000.10_114_192_34_80.Diagnostics.TimeoutErrors",
              "db": true,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 0,
              "$count": 0,
              "$parent": 1725374914414,
              "$level": 3
          },
          {
              "scale": "",
              "action": 1,
              "m": "",
              "id": "8b04393c-5ed7-4e9a-987c-9baf74806069",
              "name": "Общее число тэгов полученных из INI",
              "desc": "Общее число тэгов полученных из INI",
              "link": "ECOM3000.10_114_192_34_80.Diagnostics.TotalTagsCount",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 0,
              "$count": 0,
              "$parent": 1725374914414,
              "$level": 3
          },
          {
              "scale": "",
              "action": 1,
              "m": "",
              "id": "508f46c0-4b69-44a6-8563-1427a15ed81e",
              "name": "Локальное время УСПД",
              "desc": "Локальное время УСПД",
              "link": "ECOM3000.10_114_192_34_80.Diagnostics.USPDLocalTime",
              "db": true,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 0,
              "$count": 0,
              "$parent": 1725374914414,
              "$level": 3
          },
          {
              "scale": "",
              "action": 1,
              "m": "",
              "id": "39b69ba0-cdcc-4e5f-b2de-d98bc3cd10e0",
              "name": "Часовой пояс УСПД (в минутах)",
              "desc": "Часовой пояс УСПД (в минутах)",
              "link": "ECOM3000.10_114_192_34_80.Diagnostics.USPDLocalTimeZone",
              "db": true,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 0,
              "$count": 0,
              "$parent": 1725374914414,
              "$level": 3
          }
      ],
      "passport": {
          "staticData": [],
          "parameters": []
      },
      "maintenance": {
          "enabled": false,
          "isAcknowledged": false,
          "triggeredParameters": [],
          "source": 0,
          "warningDate": "2024-05-31T10:35:13.8460000Z",
          "alarmDate": "2024-05-31T10:35:13.8460000Z",
          "parameters": [],
          "isPending": false
      },
      "pages": [
          {
              "id": "3b611b58-2bd1-4423-81af-4e4fe6d4a635",
              "hdr": "Параметры",
              "params": [
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "ebf503f2-7c96-4fa9-abf7-efa5030d11fc",
                      "name": "Мод2 вых1",
                      "desc": "Мод2 вых1",
                      "link": "ModbusRTUMaster.COM27.Device7.DiscrOutputs.Tagou1",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 3,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "6cb13b7c-9e45-4b65-a0f9-e1f1d5fdb75a",
                      "name": "Мод2 вых2",
                      "desc": "Мод2 вых2",
                      "link": "ModbusRTUMaster.COM27.Device7.DiscrOutputs.Tagou2",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 3,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "aec1bff8-046b-4d1a-a2b8-a839c1816d62",
                      "name": "Мод2 вых3",
                      "desc": "Мод2 вых3",
                      "link": "ModbusRTUMaster.COM27.Device7.DiscrOutputs.Tagou3",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 3,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "bd36ed2b-43ba-4ab7-894f-b4d06d39f77c",
                      "name": "Мод2 вых4",
                      "desc": "Мод2 вых4",
                      "link": "ModbusRTUMaster.COM27.Device7.DiscrOutputs.Tagou4",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 3,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "5f82fea9-a550-4896-82f9-a8646fb3606e",
                      "name": "Мод2 вых5",
                      "desc": "Мод2 вых5",
                      "link": "ModbusRTUMaster.COM27.Device7.DiscrOutputs.Tagou5",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 3,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "ad265e62-c348-4c8b-8611-45e427946154",
                      "name": "Мод2 вых6",
                      "desc": "Мод2 вых6",
                      "link": "ModbusRTUMaster.COM27.Device7.DiscrOutputs.Tagou6",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 3,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "45d224c6-7e2b-4dc4-8302-0b48d30e2ab7",
                      "name": "Мод2 вых7",
                      "desc": "Мод2 вых7",
                      "link": "ModbusRTUMaster.COM27.Device7.DiscrOutputs.Tagou7",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 3,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "90cdee0c-4c75-4316-8b99-c4855d793636",
                      "name": "Мод2 вых8",
                      "desc": "Мод2 вых8",
                      "link": "ModbusRTUMaster.COM27.Device7.DiscrOutputs.Tagou8",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 3,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "fa54e0c9-ffff-4e6f-937c-fbef5d47d45c",
                      "name": "Мод2 вых9",
                      "desc": "Мод2 вых9",
                      "link": "ModbusRTUMaster.COM27.Device7.DiscrOutputs.Tagou9",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 3,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "fba16bcc-f9f3-4b3c-a09d-26eb0e3a0155",
                      "name": "Мод2 вых10",
                      "desc": "Мод2 вых10",
                      "link": "ModbusRTUMaster.COM27.Device7.DiscrOutputs.Tagou10",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 3,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "0ecc5d85-8841-4d2e-9969-7262e84dc03e",
                      "name": "Мод2 вых11",
                      "desc": "Мод2 вых11",
                      "link": "ModbusRTUMaster.COM27.Device7.DiscrOutputs.Tagou11",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 3,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "8534f413-cbf2-41ec-8f57-8a71408801fd",
                      "name": "Мод2 вых12",
                      "desc": "Мод2 вых12",
                      "link": "ModbusRTUMaster.COM27.Device7.DiscrOutputs.Tagou12",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 3,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "4146a567-27ce-472e-8cc2-171413460b4f",
                      "name": "Мод2 вых13",
                      "desc": "Мод2 вых13",
                      "link": "ModbusRTUMaster.COM27.Device7.DiscrOutputs.Tagou13",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 3,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "c38d379f-5888-40b2-86fe-88272587e301",
                      "name": "Мод2 вых14",
                      "desc": "Мод2 вых14",
                      "link": "ModbusRTUMaster.COM27.Device7.DiscrOutputs.Tagou14",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 3,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "54b6a307-c17a-455c-95f8-688ffab4859d",
                      "name": "Мод2 вых15",
                      "desc": "Мод2 вых15",
                      "link": "ModbusRTUMaster.COM27.Device7.DiscrOutputs.Tagou15",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 3,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "90df7b84-b692-4456-986d-2792096c99fc",
                      "name": "Мод2 вых16",
                      "desc": "Мод2 вых16",
                      "link": "ModbusRTUMaster.COM27.Device7.DiscrOutputs.Tagou16",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 3,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "4332812c-9e09-42ef-8f64-e8190643c9b2",
                      "name": "Мод4 вых1",
                      "desc": "Мод4 вых1",
                      "link": "ModbusRTUMaster.COM27.Device7.DiscrOutputs.Tagou17",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 3,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "a3eaee5d-8a5f-4a50-9159-0dc441460c85",
                      "name": "Мод4 вых2",
                      "desc": "Мод4 вых2",
                      "link": "ModbusRTUMaster.COM27.Device7.DiscrOutputs.Tagou18",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 3,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "ade5d96d-7976-4197-8728-c1e1574790f2",
                      "name": "Мод4 вых3",
                      "desc": "Мод4 вых3",
                      "link": "ModbusRTUMaster.COM27.Device7.DiscrOutputs.Tagou19",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 3,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "f338e19b-d1ac-48ed-859b-8f29188077ce",
                      "name": "Мод4 вых4",
                      "desc": "Мод4 вых4",
                      "link": "ModbusRTUMaster.COM27.Device7.DiscrOutputs.Tagou20",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 3,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "3836a129-cbd6-49ea-8a50-5514f3185f8d",
                      "name": "Мод4 вых5",
                      "desc": "Мод4 вых5",
                      "link": "ModbusRTUMaster.COM27.Device7.DiscrOutputs.Tagou21",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 3,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "6c161e89-1614-470a-a72f-89a2d5da172c",
                      "name": "Мод4 вых6",
                      "desc": "Мод4 вых6",
                      "link": "ModbusRTUMaster.COM27.Device7.DiscrOutputs.Tagou22",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 3,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "263d2219-fb0b-452c-aae2-b1a9e193d6b5",
                      "name": "Мод4 вых7",
                      "desc": "Мод4 вых7",
                      "link": "ModbusRTUMaster.COM27.Device7.DiscrOutputs.Tagou23",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 3,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "dfc26db8-0ad6-4c01-84e6-654c1782a07e",
                      "name": "Мод4 вых8",
                      "desc": "Мод4 вых8",
                      "link": "ModbusRTUMaster.COM27.Device7.DiscrOutputs.Tagou24",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 3,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "799839cf-861d-46d6-bed0-bf0246a8d670",
                      "name": "Мод7 вых1",
                      "desc": "Мод7 вых1",
                      "link": "ModbusRTUMaster.COM27.Device7.DiscrOutputs.Tagou25",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 3,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "3fb111e6-730d-4432-88fa-bd38d51ebacd",
                      "name": "Мод7 вых2",
                      "desc": "Мод7 вых2",
                      "link": "ModbusRTUMaster.COM27.Device7.DiscrOutputs.Tagou26",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 3,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "ac167a3e-8ae1-4db6-af18-68c969029c10",
                      "name": "Мод7 вых3",
                      "desc": "Мод7 вых3",
                      "link": "ModbusRTUMaster.COM27.Device7.DiscrOutputs.Tagou27",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 3,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "af10e340-932d-4fb6-8966-b6152102a7b7",
                      "name": "Мод7 вых4",
                      "desc": "Мод7 вых4",
                      "link": "ModbusRTUMaster.COM27.Device7.DiscrOutputs.Tagou28",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 3,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "e0b2682e-b691-4fa5-810b-1694f42b4d6a",
                      "name": "Мод7 вых5",
                      "desc": "Мод7 вых5",
                      "link": "ModbusRTUMaster.COM27.Device7.DiscrOutputs.Tagou29",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 3,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "aa25808c-fee9-460e-859a-cc81f137ea4e",
                      "name": "Мод7 вых6",
                      "desc": "Мод7 вых6",
                      "link": "ModbusRTUMaster.COM27.Device7.DiscrOutputs.Tagou30",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 3,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "e56c9f3c-927e-47b8-8361-8c3c291932f1",
                      "name": "Мод7 вых7",
                      "desc": "Мод7 вых7",
                      "link": "ModbusRTUMaster.COM27.Device7.DiscrOutputs.Tagou31",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 3,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "3e5830a3-5bcc-4391-8ba7-e3ceec314c20",
                      "name": "выход 2",
                      "desc": "выход 2",
                      "link": "ModbusRTUMaster.COM27.Device7.AO.Tagao3",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 7,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "669d39f0-0f93-4ec3-8bcf-1741916a128b",
                      "name": "Мод7 вых8",
                      "desc": "Мод7 вых8",
                      "link": "ModbusRTUMaster.COM27.Device7.DiscrOutputs.Tagou32",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 3,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "8e744ded-c776-490d-8458-855bce34ac80",
                      "name": "выход 1",
                      "desc": "выход 1",
                      "link": "ModbusRTUMaster.COM27.Device7.AO.Tagao1",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 7,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "9cf0df26-2a7e-465e-b7ab-db7afd3d0fcd",
                      "name": "выход 1+",
                      "desc": "выход 1+",
                      "link": "ModbusRTUMaster.COM27.Device7.AO.Tagao2",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 7,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  },
                  {
                      "scale": "",
                      "action": 1,
                      "m": "",
                      "id": "09e403b3-990c-41e6-a474-68cf0f9bbf79",
                      "name": "выход 2+",
                      "desc": "выход 2+",
                      "link": "ModbusRTUMaster.COM27.Device7.AO.Tagao4",
                      "db": false,
                      "inf": false,
                      "wrn": false,
                      "err": false,
                      "alm": false,
                      "ntf": false,
                      "inv": false,
                      "mnt": false,
                      "vtype": 7,
                      "$count": 0,
                      "$parent": 1725374914416,
                      "$level": 4
                  }
              ]
          }
      ],
      "state": "UNKNOWN",
      "eq": true,
      "$count": 9,
      "$parent": 0,
      "$level": 1
  },
  {
      "id": "3d18f9a1-d636-4dbd-99f9-eab5b1d834fb",
      "type": "SWITCH",
      "ver": "3.0",
      "name": "Выключатель",
      "icon": "switch.png",
      "desc": "Выключатель",
      "files": {
          "mid": "00000000-0000-0000-0000-000000000000",
          "sid": "00000000-0000-0000-0000-000000000000",
          "jrn": false,
          "osc": false
      },
      "reports": {
          "state": false,
          "maint": false
      },
      "altname": "",
      "states": [
          {
              "visible": true,
              "system": false,
              "id": "2040bced-7a30-4d4e-a71e-9bfc1964d910",
              "name": "ON",
              "desc": "Включен",
              "link": "VirtualDevices.Имитатор.Device3.Parameter.Mu",
              "db": true,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 3,
              "state": true,
              "$count": 0,
              "$parent": 1725374914433,
              "$level": 3
          },
          {
              "visible": true,
              "system": false,
              "id": "57660a7f-abc3-4f93-8750-c029e63d858b",
              "name": "OFF",
              "desc": "Отключен",
              "link": "",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 0,
              "state": true,
              "$count": 0,
              "$parent": 1725374914433,
              "$level": 3
          },
          {
              "visible": false,
              "system": false,
              "id": "87e1e695-15b1-4627-8331-357317c38e6c",
              "name": "ERROR",
              "desc": "Недостоверно",
              "link": "",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 0,
              "state": true,
              "$count": 0,
              "$parent": 1725374914433,
              "$level": 3
          },
          {
              "visible": false,
              "system": false,
              "id": "30736bb8-933d-4887-acc9-98c2103f3e94",
              "name": "DAMAGE",
              "desc": "Авария/Неисправность",
              "link": "",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 0,
              "state": true,
              "$count": 0,
              "$parent": 1725374914433,
              "$level": 3
          },
          {
              "visible": true,
              "system": false,
              "id": "3080b224-bd7e-4b4c-8272-efdc95be77c0",
              "name": "SERVICE",
              "desc": "В ремонте",
              "link": "",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 0,
              "state": true,
              "$count": 0,
              "$parent": 1725374914433,
              "$level": 3
          },
          {
              "visible": true,
              "system": false,
              "id": "be7cc277-30df-45d1-8c22-8fa633a57c45",
              "name": "BLOCK",
              "desc": "Опер. блокировка",
              "link": "",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 0,
              "state": true,
              "$count": 0,
              "$parent": 1725374914433,
              "$level": 3
          },
          {
              "visible": true,
              "system": false,
              "id": "793b3f30-015f-464c-a71d-a7b118acc0cc",
              "name": "MANUAL",
              "desc": "Ручное управление",
              "link": "",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 0,
              "state": true,
              "$count": 0,
              "$parent": 1725374914433,
              "$level": 3
          },
          {
              "visible": false,
              "system": true,
              "id": "b07dff48-ae39-423d-a248-5d0c5f82a1be",
              "name": "$MAINT_WARN",
              "desc": "Необходимо обслуживание",
              "link": "b07dff48-ae39-423d-a248-5d0c5f82a1be",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 3,
              "state": true,
              "$count": 0,
              "$parent": 1725374914433,
              "$level": 3
          },
          {
              "visible": false,
              "system": true,
              "id": "7f3fa103-3e04-42a1-b06f-9d8a57e67160",
              "name": "$MAINT_ALARM",
              "desc": "Аварийное (необходимо обслуживание)",
              "link": "7f3fa103-3e04-42a1-b06f-9d8a57e67160",
              "db": false,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 3,
              "state": true,
              "$count": 0,
              "$parent": 1725374914433,
              "$level": 3
          }
      ],
      "commands": [
          {
              "icon": "cmd/sw_on.png",
              "cnf": false,
              "id": "0a9960f5-62f4-4d7b-8845-457fbf6fd825",
              "name": "Включить",
              "desc": "Включить",
              "link": "VirtualDevices.Имитатор.Device3.Commands.Mu_ON",
              "db": true,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 3,
              "cmd": true,
              "$count": 0,
              "$parent": 1725374914434,
              "$level": 3
          },
          {
              "icon": "cmd/sw_off.png",
              "cnf": false,
              "id": "cb9f11c2-064b-488b-9183-00610c2b1ac2",
              "name": "Отключить",
              "desc": "Отключить",
              "link": "VirtualDevices.Имитатор.Device3.Commands.Mu_OFF",
              "db": true,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 3,
              "cmd": true,
              "$count": 0,
              "$parent": 1725374914434,
              "$level": 3
          },
          {
              "icon": "cmd/sw_block.png",
              "cnf": false,
              "id": "376da153-5a4d-44d2-8299-e179ea3c12ba",
              "name": "Вывести в ремонт",
              "desc": "Вывести в ремонт",
              "link": "",
              "db": true,
              "inf": false,
              "wrn": false,
              "err": false,
              "alm": false,
              "ntf": false,
              "inv": false,
              "mnt": false,
              "vtype": 0,
              "cmd": true,
              "$count": 0,
              "$parent": 1725374914434,
              "$level": 3
          }
      ],
      "oper": [],
      "passport": {
          "staticData": [],
          "parameters": []
      },
      "maintenance": {
          "enabled": false,
          "isAcknowledged": false,
          "triggeredParameters": [],
          "source": 0,
          "warningDate": "2024-08-29T12:45:28.9320000Z",
          "alarmDate": "2024-08-29T12:45:28.9320000Z",
          "parameters": [],
          "isPending": false
      },
      "pages": [],
      "state": "ERROR",
      "eq": true,
      "$count": 2,
      "$parent": 0,
      "$level": 1
  }
]